language: r
cache: packages

after_success:
- Rscript -e "remotes::install_github('fvitalini/PoCbookdownPkg')"
- Rscript -e "PoCbookdownPkg::render_site()"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  local_dir: _site
  on:
    branch: master
