language: r
cache: packages
before_cache: Rscript -e 'remotes::install_cran("bookdown")'

script: Rscript -e 'cat("nothing")' # instead of the default R CMD check
after_success:
- Rscript -e "getwd()"
- Rscript -e "list.files()"
- Rscript -e "remotes::install_github('fvitalini/PoCbookdownPkg')"
- Rscript -e "PoCbookdownPkg::render_site(output_dir = '_site')"
- Rscript -e "getwd()"
- Rscript -e "list.files()"
- Rscript -e "list.files(recursive = TRUE)"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT  # Set in the settings page of your repository, as a secure variable
  local_dir: _site
  on:
    branch: master
